2024-10-30 00:14:21,007 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/nksound/Documents/PYTHON PROJECT/MODULE_12/tests_12_4.py", line 24, in test_run
    runner = Runner(123, speed=10)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nksound/Documents/PYTHON PROJECT/MODULE_12/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-30 00:14:21,008 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/nksound/Documents/PYTHON PROJECT/MODULE_12/tests_12_4.py", line 14, in test_walk
    runner = Runner('TestWalk', speed=-1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nksound/Documents/PYTHON PROJECT/MODULE_12/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
